theme: jekyll-theme-minimal
title: Just another page for Machine Learning stuff
description: This site is a homapage for all my projects and future blogs. I am passionate about Machine Learning, Deep Learning and Natural Language Processing.
